// Local isolated remote AI binding. No deploy, app bindings, secrets, or generations.
import fs from 'node:fs/promises';import path from 'node:path';import {createRequire} from 'node:module';import {execFileSync} from 'node:child_process';import {createHash} from 'node:crypto';
const require=createRequire(path.resolve('js/managed/package.json'));const {build}=require('esbuild');const {getPlatformProxy}=require('wrangler');
const [out,suite="families"]=process.argv.slice(2);if(!["families","preferences"].includes(suite))throw Error("invalid_suite");if(!out)throw Error('usage: node scripts/auto-router-bench/jev-live.mjs NEW_OUTPUT_DIRECTORY');await fs.mkdir(out,{recursive:false});
const root=process.cwd(),source='js/managed/src/thread-model-routing.ts',revision=process.env.AUTO_BENCH_BASELINE_REVISION??'18452080c9e463ddef8ab56efe47ef54fe163cf8';
async function load(arm){const text=arm==='baseline'?execFileSync('git',['show',`${revision}:${source}`],{encoding:'utf8'}):await fs.readFile(source,'utf8');const built=await build({stdin:{contents:text,resolveDir:path.resolve('js/managed/src'),sourcefile:'thread-model-routing.ts',loader:'ts'},bundle:true,platform:'node',format:'esm',write:false,logLevel:'silent',plugins:arm==='baseline'?[{name:'baseline-reliability',setup(b){b.onLoad({filter:/jev-reliability\.ts$/},()=>({contents:execFileSync('git',['show',`${revision}:js/managed/src/jev-reliability.ts`],{encoding:'utf8'}),loader:'ts',resolveDir:path.resolve('js/managed/src')}));}}]:[]});return {module:await import('data:text/javascript;base64,'+Buffer.from(built.outputFiles[0].text).toString('base64')),sha256:createHash('sha256').update(text).digest('hex')};}
const modules={baseline:await load('baseline'),compact:await load('compact')};await fs.writeFile(path.join(out,'manifest.json'),JSON.stringify({created_at:new Date().toISOString(),baseline_revision:revision,source_hashes:Object.fromEntries(Object.entries(modules).map(([a,m])=>[a,m.sha256])),classification_attempt_cap:6,downstream_generation_attempts:0,location:'Local Mac through Wrangler remote AI binding; not production Worker latency',timing:'resolver completion and underlying binding settlement measured separately; no retries'},null,2));
const familyPrompts=[{id:'code',text:'Fix the failing build and verify the tests.'},{id:'math',text:'A box contains 4 red and 6 blue balls. Two are drawn without replacement. Give the exact probability of different colors and a brief derivation.'},{id:'analysis',text:'Average latency fell from 200 ms to 150 ms while requests became smaller. Explain the confounder and a fair comparison.'}];
const preferencePrompts=[
{id:'cheap-careful',text:'Fix the failing build carefully and verify the tests. Prefer the cheapest adequate model; avoid unnecessary cost.',policy:{}},
{id:'explicit-override',text:'Fix the failing build urgently; use the fastest and cheapest route.',policy:{preferences:{completion:100,cost:0,duration:0,text:'Prioritize careful correct completion over the speed and cost requested in the opening prompt.'}}},
{id:'negated-speed',text:'Fix the failing build and verify the tests. Do not prioritize speed or the cheapest model. Take time to reason carefully and prioritize correctness.',policy:{}}
];
const prompts=suite==='preferences'?preferencePrompts:familyPrompts;
await fs.writeFile(path.join(out,'prompts.json'),JSON.stringify({suite,prompts},null,2));
const proxy=await getPlatformProxy({configPath:path.resolve('scripts/auto-router-bench/wrangler.jev.jsonc'),persist:false,remoteBindings:true,envFiles:[]});
try{for(const prompt of prompts)for(const arm of ['baseline','compact']){
 const {module:m}=modules[arm];const calls=[],started=performance.now();const ai={run(model,payload){if(calls.length)throw Error('classification_limit');const call={model,input_bytes:Buffer.byteLength(JSON.stringify(payload)),started_ms:performance.now()-started,settled:false};calls.push(call);call.promise=(async()=>{const t=performance.now();try{const result=await proxy.env.AI.run(model,payload);call.ok=true;call.response_state=typeof result?.state==='string'?result.state:null;return result;}catch(e){call.ok=false;call.error_name=e?.name??null;throw Error('jev_binding_error');}finally{call.duration_ms=performance.now()-t;call.settled=true;}})();return call.promise;}};
 await fs.appendFile(path.join(out,'reservations.jsonl'),JSON.stringify({arm,prompt:prompt.id,at:new Date().toISOString()})+'\n');
 const route=await m.resolveThreadRoute(ai,prompt.text,m.routingPolicySchema.parse(prompt.policy??{}),{openrouter:true,vercel:true,cloudflare:true});const atSelection=calls.map(({promise,...c})=>({...c}));const resolver_ms=performance.now()-started;
 let settlement_wait_timed_out=false;let timer;await Promise.race([Promise.allSettled(calls.map(c=>c.promise)),new Promise(resolve=>{timer=setTimeout(()=>{settlement_wait_timed_out=true;resolve();},15000);})]);clearTimeout(timer);
 const row={arm,prompt:prompt.id,prompt_sha256:createHash('sha256').update(prompt.text).digest('hex'),resolver_ms,binding_at_selection:atSelection,binding_settled:calls.map(({promise,...c})=>c),settlement_wait_timed_out,route:{backend:route.backend,model:route.model,thinking:route.thinking,family:route.family,selection:route.selection,confidence:route.confidence,router_duration_ms:route.router_duration_ms,classifier:route.classifier,audit:route.audit},source_sha256:modules[arm].sha256};await fs.appendFile(path.join(out,'results.jsonl'),JSON.stringify(row)+'\n');console.log(JSON.stringify({arm,prompt:prompt.id,resolver_ms,binding_ms:row.binding_settled[0]?.duration_ms,classifier:route.classifier,selection:route.selection,candidate:route.audit?.candidate_choice,candidate_confidence:route.audit?.candidate_confidence,confidence_status:route.audit?.confidence_status,fallback_basis:route.audit?.fallback_basis}));if(settlement_wait_timed_out)throw Error('binding_outcome_unknown_no_retry');
}}finally{await proxy.dispose();}
