// Offline, usage-based comparison. Costs are estimates on reported model tokens.
import {readFileSync,writeFileSync,mkdirSync,existsSync} from 'node:fs';import {dirname,join,resolve} from 'node:path';import {createHash} from 'node:crypto';
const inputs=process.argv.slice(2);if(!inputs.length)throw Error('Supply one or more benchmark JSON files');
const reports=inputs.map(p=>JSON.parse(readFileSync(p,'utf8')));const directory=dirname(resolve(inputs[0]));
const metricFile=join(directory,'cloudflare-metrics.json');const infrastructure=existsSync(metricFile)?JSON.parse(readFileSync(metricFile,'utf8')):undefined;
const sessionMetrics=new Map();for(const r of infrastructure?.data?.sessions??[]){const key=r.dimensions.name,prior=sessionMetrics.get(key)??{duration:0,cpuTime:0,rowsRead:0,rowsWritten:0,colos:[]};for(const field of ['duration','cpuTime','rowsRead','rowsWritten'])prior[field]+=r.sum[field]??0;prior.colos=[...new Set([...prior.colos,r.dimensions.coloCode])];sessionMetrics.set(key,prior);}
const sessionCounts=new Map();for(const report of reports)for(const r of report.records)if(r.session_id)sessionCounts.set(r.session_id,(sessionCounts.get(r.session_id)??0)+1);
const prices={'gpt-5.6-luna':[.2,.02,.25,1.2],'gpt-5.6-terra':[2,.2,2.5,12],'gpt-5.6-sol':[4,.4,5,20],'gpt-6-astra':[10,1,12.5,50]};
const median=xs=>{const a=xs.filter(Number.isFinite).sort((a,b)=>a-b);return a.length?(a[Math.floor(a.length/2)]+a[Math.ceil(a.length/2)-1])/2:null;};
function cost(r){const u=r.usage;const read=u?.input_tokens_details?.cached_tokens,write=u?.input_tokens_details?.cache_write_tokens;if(![u?.input_tokens,u?.output_tokens,read].every(Number.isFinite))return null;const [i,c,w,o]=prices[r.model],tier=r.reported_tier??r.tier,factor=['fast','priority'].includes(tier)?2:1,ordinary=u.input_tokens-read-(write??0);if(ordinary<0)throw Error('Invalid cache categories');const low=(ordinary*i+read*c+(write??0)*w+u.output_tokens*o)*factor/1e6;return {low,high:low+(write===undefined?ordinary*(w-i)*factor/1e6:0),cache_write_known:write!==undefined,tier_assumed:r.reported_tier===undefined};}
const rows=reports.flatMap(report=>report.records.map(r=>{const {events,...rest}=r;return {...rest,label:report.label,delegation:report.delegation??'default',managed_url:report.managed_url,managed_version:report.managed_version,cost:cost(r),
 cloudflare_session:sessionMetrics.has(r.session_id)?{...sessionMetrics.get(r.session_id),shared_between_measured_turns:sessionCounts.get(r.session_id)>1,unrounded_duration_and_sql_usd:(m=>m.duration*12.5/1e6+m.rowsRead*.001/1e6+m.rowsWritten/1e6)(sessionMetrics.get(r.session_id)),analytics_retrieved_at:infrastructure.retrieved_at}:null,
 model_elapsed_ms:r.run?.model_duration_ns===undefined?null:r.run.model_duration_ns/1e6,
 connection_ms:r.run?.connection_duration_ns===undefined?null:r.run.connection_duration_ns/1e6,
 pre_model_ms:r.model_started_ms??null,
 post_text_ms:r.last_text_ms==null||r.completion_ms==null?null:r.completion_ms-r.last_text_ms,
 root_model_calls:r.run?.model_calls??null,root_tool_calls:r.run?.tool_calls??null,reported_model_calls:r.model_calls?.length??null,
 visible_characters_per_second:r.streaming_ms>0?(r.visible_characters-(r.first_delta_characters??0))/(r.streaming_ms/1000):null,
 event_count:events?.length??0,
 };}));
const map=new Map();for(const r of rows){const key=JSON.stringify([r.label,r.path,r.model,r.effort,r.tier,r.workload,r.state]);const group=map.get(key)??[];group.push(r);map.set(key,group);}
const groups=[...map.values()].map(rs=>{const r=rs[0],ok=rs.filter(x=>x.terminal==='completed'&&!x.error),correct=ok.filter(x=>x.correct);const metrics={};
 for(const field of ['ttft_ms','completion_ms','create_ms','accepted_ms','model_started_ms','model_elapsed_ms','connection_ms','post_text_ms','streaming_ms','visible_characters_per_second']){const values=ok.map(x=>x[field]).filter(Number.isFinite);metrics[field]={median:median(values),min:values.length?Math.min(...values):null,max:values.length?Math.max(...values):null,n:values.length};}
 return {...Object.fromEntries(['label','path','model','effort','tier','workload','state'].map(k=>[k,r[k]])),n:rs.length,completed:ok.length,correct:correct.length,metrics,
 input_tokens:median(ok.map(x=>x.usage?.input_tokens)),output_tokens:median(ok.map(x=>x.usage?.output_tokens)),reasoning_tokens:median(ok.map(x=>x.usage?.output_tokens_details?.reasoning_tokens)),cached_tokens:median(ok.map(x=>x.usage?.input_tokens_details?.cached_tokens)),cache_write_tokens:median(ok.map(x=>x.usage?.input_tokens_details?.cache_write_tokens)),cost_low:median(ok.map(x=>x.cost?.low)),cost_high:median(ok.map(x=>x.cost?.high)),errors:rs.filter(x=>x.error).map(x=>x.error)};
});
const summary={generated_at:new Date().toISOString(),sources:inputs.map((p,i)=>({file:p,sha256:createHash('sha256').update(readFileSync(p)).digest('hex'),managed_version:reports[i].managed_version,delegation:reports[i].delegation??'default',max_checkpoint_ms:reports[i].max_checkpoint_ms??null,concurrency:reports[i].concurrency,started_at:reports[i].started_at,finished_at:reports[i].finished_at,complete:reports[i].complete,expected_records:reports[i].expected_records})),workload_contracts:reports.map(report=>({label:report.label,instructions:report.instructions,workloads:report.workloads})),trials:rows.length,completed:rows.filter(r=>r.terminal==='completed'&&!r.error).length,correct:rows.filter(r=>r.correct).length,cleanup_unconfirmed:rows.filter(r=>r.session_id&&!r.deleted).length,usage_missing:rows.filter(r=>!r.usage).length,cost_unknown:rows.filter(r=>!r.cost).length,model_subtotal_low:rows.reduce((n,r)=>n+(r.cost?.low??0),0),model_subtotal_high:rows.reduce((n,r)=>n+(r.cost?.high??0),0),pricing_source:'https://developers.openai.com/api/docs/pricing',pricing_checked:'2026-09-11',groups};
writeFileSync(join(directory,'summary.json'),JSON.stringify(summary,null,2)+'\n');writeFileSync(join(directory,'measurements.json'),JSON.stringify({sources:summary.sources,records:rows},null,2)+'\n');
const sec=n=>n==null?'—':(n/1000).toFixed(3);const table=['| Label | Model | Effort | Tier | Workload | State | Path | Correct / n | TTFT p50 (s) | Completion p50 (s) | Completion min–max (s) | Input / output / reasoning tokens p50 | Model cost p50 (USD) |','| --- | --- | --- | --- | --- | --- | --- | ---: | ---: | ---: | --- | --- | --- |'];
for(const g of groups)table.push(`| ${g.label} | ${g.model} | ${g.effort} | ${g.tier} | ${g.workload} | ${g.state} | ${g.path} | ${g.correct}/${g.n} | ${sec(g.metrics.ttft_ms.median)} | ${sec(g.metrics.completion_ms.median)} | ${sec(g.metrics.completion_ms.min)}–${sec(g.metrics.completion_ms.max)} | ${g.input_tokens??'—'} / ${g.output_tokens??'—'} / ${g.reasoning_tokens??'—'} | ${g.cost_low?.toFixed(6)??'unknown'}–${g.cost_high?.toFixed(6)??'unknown'} |`);
writeFileSync(join(directory,'TABLE.md'),table.join('\n')+'\n');console.log(JSON.stringify({...summary,groups:groups.length,sources:inputs.length,workload_contracts:summary.workload_contracts.length}));
