#!/usr/bin/env python3
"""Pin every prompt asset and renderer in the declared upstream inventory.

Run with an official checkout at PIN; --write regenerates exact assets and bindings.
Unknown/new source files fail verification rather than being silently skipped.
Runtime availability is recorded separately from source-byte parity.
"""
import argparse
import hashlib
import json
from pathlib import Path
import subprocess

PIN = '36430b36881cf5c289cb48e671cfc9e8b542ae7b'
ROOT = Path(__file__).resolve().parents[2]
DEST = ROOT / 'crates/nanocodex-oai-api/prompts/codex'
# Entire source directories are included so inline messages and renderer branches
# are reviewed too. These are evidence; only assets belong to the runtime registry.
TREES = ['prompts', 'collaboration-mode-templates', 'core/templates', 'core/assets',
         'core/src/context', 'memories/read/src', 'memories/write/src',
         'memories/write/templates', 'ext/goal/src', 'ext/goal/templates',
         'ext/memories/src', 'ext/memories/templates', 'utils/template/src', 'context-fragments/src']
EXTRA = ['models-manager/models.json', 'models-manager/prompt.md',
         'models-manager/src/model_info.rs', 'models-manager/src/collaboration_mode_presets.rs',
         'core/src/agents_md.rs', 'core/src/plugins/render.rs', 'ext/skills/src/render.rs',
         'tui/assets/prompt_for_init_command.md']

def inventory(upstream):
    base = upstream / 'codex-rs'
    paths = set()
    for tree in TREES:
        assert (base / tree).is_dir(), tree
        paths.update(p for p in (base / tree).rglob('*') if p.is_file())
    for path in EXTRA:
        assert (base / path).is_file(), path
        paths.add(base / path)
    paths.update(base.joinpath('core').glob('*prompt.md'))
    return {str(p.relative_to(base)): p.read_bytes() for p in sorted(paths)}

def asset(path):
    return (('/templates/' in path or path.startswith('collaboration-mode-templates/templates/'))
            and not path.endswith(('.rs', '.toml', '.bazel'))) or path.endswith('prompt.md') or path == 'tui/assets/prompt_for_init_command.md'

def status(path):
    if path == 'models-manager/models.json': return 'catalog: four supported model instructions consumed natively and through WASM; all catalog message fields retained'
    if path.startswith('ext/goal/templates/'): return 'continuation consumed by managed JS; objective-update and budget-limit renderers exposed, dispatch not integrated'
    if 'permissions/' in path: return 'bundled permissions rendered by native unrestricted execution; hosted grants must be supplied by host'
    if 'realtime/' in path: return 'voice protocol native and WASM consumers'
    if 'multi_agent' in path or '/agent' in path or '/collab/' in path: return 'custom-subagent exception pending root resolution; evidence only'
    return 'source inventory; renderer/asset API available where applicable; no claim of mode dispatch support'

def outputs(files):
    assets = {p: b.decode() for p,b in files.items() if asset(p)}
    models = json.loads(files['models-manager/models.json'])['models']
    def catalog_strings(value, path):
        if isinstance(value, str): assets[path + '.txt'] = value
        elif isinstance(value, dict):
            for key, child in value.items(): catalog_strings(child, path + '/' + key)
    for model in models:
        catalog_strings(model.get('model_messages', {}), 'catalog/' + model['slug'])
        for family, value in model.get('model_messages', {}).items():
            if family == 'instructions_template' and value is not None:
                assets['models/' + model['slug'] + '.md'] = value
    manifest = {'upstream': PIN, 'source_roots': TREES, 'extra_sources': EXTRA,
                'sources': [{'path': p, 'sha256': hashlib.sha256(b).hexdigest(), 'bytes': len(b), 'availability': status(p)} for p,b in files.items()],
                'assets': [{'path': p, 'sha256': hashlib.sha256(s.encode()).hexdigest()} for p,s in sorted(assets.items())]}
    generated = {DEST / p: b for p,b in files.items()}
    generated.update({DEST / p: s.encode() for p,s in assets.items()})
    generated[DEST / 'manifest.json'] = (json.dumps(manifest, indent=2) + '\n').encode()
    generated[ROOT / 'js/managed/src/codex-prompt-assets.ts'] = ('// Generated by scripts/codex-parity/prompts.py; exact UTF-8 assets.\nexport const CODEX_PROMPT_PIN = ' + json.dumps(PIN) + ';\nexport const CODEX_PROMPT_ASSETS: Readonly<Record<string, string>> = ' + json.dumps(assets, ensure_ascii=False, indent=2) + ';\n').encode()
    rust = '//! Generated canonical prompt lookup. Do not edit; run scripts/codex-parity/prompts.py.\n'
    rust += '/// Official upstream revision.\npub const UPSTREAM: &str = "' + PIN + '";\n'
    rust += '/// Every inventoried prompt asset, including unsupported modes.\npub const ASSETS: &[(&str, &str)] = &[\n'
    rust += ''.join('    (' + json.dumps(p) + ', include_str!("../prompts/codex/' + p + '")),\n' for p in sorted(assets))
    rust += '];\n/// Return exact source bytes as UTF-8, without normalization or branding.\npub fn asset(path: &str) -> Option<&\'static str> {\n    ASSETS.iter().find(|(name, _)| *name == path).map(|(_, text)| *text)\n}\n'
    generated[ROOT / 'crates/nanocodex-oai-api/src/prompt_assets.rs'] = rust.encode()
    generated[ROOT / 'crates/nanocodex-oai-api/prompts/astra.md'] = assets['models/gpt-6-astra.md'].encode()
    legacy = [assets['models/' + slug + '.md'] for slug in ['gpt-5.6-sol','gpt-5.6-terra','gpt-5.6-luna']]
    assert len(set(legacy)) == 1, 'models no longer share legacy template; split runtime mapping'
    generated[ROOT / 'crates/nanocodex-oai-api/prompts/system.md'] = legacy[0].encode()
    voice = '// Generated from the pinned upstream Realtime assets and fragment renderer.\n'
    for name, path in [('CHATGPT_REALTIME_BACKEND_PROMPT_TEMPLATE', 'backend_prompt.md'), ('REALTIME_START_INSTRUCTIONS', 'realtime_start.md'), ('REALTIME_END_INSTRUCTIONS', 'realtime_end.md')]:
        content = assets['prompts/templates/realtime/' + path]
        if path != 'backend_prompt.md': content = '<realtime_conversation>\n' + content.strip() + '\n</realtime_conversation>'
        voice += '/// Canonical upstream Realtime prompt.\npub const ' + name + ': &str = ' + json.dumps(content, ensure_ascii=False) + ';\n'
    generated[ROOT / 'crates/nanocodex-voice-protocol/src/canonical_prompts.rs'] = voice.encode()
    generated[ROOT / 'crates/nanocodex-voice-protocol/src/backend_prompt.md'] = assets['prompts/templates/realtime/backend_prompt.md'].encode()
    return generated

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('upstream', type=Path)
    parser.add_argument('--write', action='store_true')
    args = parser.parse_args()
    assert subprocess.check_output(['git','-C',str(args.upstream),'rev-parse','HEAD'], text=True).strip() == PIN
    assert not subprocess.check_output(['git','-C',str(args.upstream),'status','--porcelain','--untracked-files=no'], text=True).strip(), 'modified upstream'
    files = inventory(args.upstream)
    expected = outputs(files)
    for path, content in expected.items():
        if args.write:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(content)
        else:
            assert path.read_bytes() == content, f'prompt drift: {path.relative_to(ROOT)}'
    actual = {p for p in DEST.rglob('*') if p.is_file()}
    assert actual == {p for p in expected if p.is_relative_to(DEST)}, 'unmanifested canonical source files'
    print(f'PASS {len(files)} exact upstream sources; {len(expected)} generated files; {PIN}')
