#!/usr/bin/env python3
"""Verify only consumed runtime prompts against a clean external Codex checkout.

No upstream source code or model catalog is vendored. --write refreshes the small
set of runtime assets and their provenance; verification compares exact bytes.
"""
import argparse
import hashlib
import json
from pathlib import Path
import subprocess

PIN = '36430b36881cf5c289cb48e671cfc9e8b542ae7b'
ROOT = Path(__file__).resolve().parents[2]
MANIFEST = ROOT / 'scripts/codex-parity/prompts.json'
# source -> actual consuming asset (no optional prompt inventory)
FILES = {
    'prompts/templates/permissions/sandbox_mode/danger_full_access.md':
        'crates/nanocodex-agent/src/model/prompts/danger_full_access.md',
    'prompts/templates/permissions/approval_policy/never.md':
        'crates/nanocodex-agent/src/model/prompts/never.md',
    'prompts/templates/realtime/backend_prompt.md':
        'crates/nanocodex-voice-protocol/src/backend_prompt.md',
    'prompts/templates/realtime/realtime_start.md':
        'crates/nanocodex-voice-protocol/src/realtime_start.md',
    'prompts/templates/realtime/realtime_end.md':
        'crates/nanocodex-voice-protocol/src/realtime_end.md',
}
GOAL = 'ext/goal/templates/goals/continuation.md'
CATALOG = 'models-manager/models.json'
# Provenance for composition rules, verified externally but never copied locally.
RENDERERS = ['prompts/src/permissions_instructions.rs', 'prompts/src/realtime.rs',
             'core/src/context/realtime_start_instructions.rs',
             'core/src/context/realtime_end_instructions.rs',
             'ext/goal/src/runtime.rs', 'utils/template/src/lib.rs']
MODELS = ['gpt-6-astra', 'gpt-5.6-sol', 'gpt-5.6-terra', 'gpt-5.6-luna']


def digest(content):
    return hashlib.sha256(content).hexdigest()


def outputs(upstream):
    base = upstream / 'codex-rs'
    sources = {p: (base / p).read_bytes() for p in [*FILES, GOAL, CATALOG, *RENDERERS]}
    generated = {ROOT / target: sources[source] for source, target in FILES.items()}
    models = {m['slug']: m for m in json.loads(sources[CATALOG])['models']}
    fields = []
    for slug in MODELS:
        content = models[slug]['model_messages']['instructions_template'].encode()
        target = 'crates/nanocodex-oai-api/prompts/' + ('astra.md' if slug == 'gpt-6-astra' else 'system.md')
        assert ROOT / target not in generated or generated[ROOT / target] == content, 'legacy models need separate templates'
        generated[ROOT / target] = content
        fields.append({'model': slug, 'field': 'model_messages.instructions_template',
                       'target': target, 'sha256': digest(content)})
    generated[ROOT / 'js/managed/src/goal-continuation.ts'] = (
        '// Generated by scripts/codex-parity/prompts.py from ' + PIN + '.\n'
        'export const GOAL_CONTINUATION_TEMPLATE = `' + sources[GOAL].decode().replace('\\', '\\\\').replace('`', '\\`').replace('${', '\\${') + '`;\n'
    ).encode()
    manifest = {
        'upstream': PIN,
        'sources': [{'path': p, 'sha256': digest(b), 'bytes': len(b),
                     'role': 'composition reference (external only)' if p in RENDERERS else 'consumed prompt source'}
                    for p, b in sorted(sources.items())],
        'model_fields': fields,
        'outputs': [{'path': str(p.relative_to(ROOT)), 'sha256': digest(b), 'bytes': len(b)}
                    for p, b in sorted(generated.items())],
    }
    generated[MANIFEST] = (json.dumps(manifest, indent=2) + '\n').encode()
    return generated


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('upstream', type=Path)
    parser.add_argument('--write', action='store_true')
    args = parser.parse_args()
    assert subprocess.check_output(['git', '-C', str(args.upstream), 'rev-parse', 'HEAD'], text=True).strip() == PIN, 'wrong upstream revision'
    assert not subprocess.check_output(['git', '-C', str(args.upstream), 'status', '--porcelain', '--untracked-files=no'], text=True).strip(), 'modified upstream'
    expected = outputs(args.upstream)
    for path, content in expected.items():
        if args.write:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(content)
        else:
            assert path.read_bytes() == content, f'prompt drift: {path.relative_to(ROOT)}'
    print(f'PASS {len(FILES) + 2} consumed upstream sources; {len(RENDERERS)} external composition references; {len(expected)} outputs; {PIN}')


if __name__ == '__main__':
    main()
